on: [push]

jobs:
  gen-image:
    runs-on: ubuntu-latest
    name: Generate images from a KiCad project
    steps:
      - uses: actions/checkout@v4
      - uses: lamemakes/kicad-pics-action@aeeb7b7e9e90a8b73901f9f4b2ec7f1c621f70c0
        with:
          project-path: './hardware/'
          project-name: 'tree-ornament'
          output-path: './pics/'
