on: [push]

jobs:
  gen-image:
    runs-on: ubuntu-latest
    name: Generate images from a KiCad project
    steps:
      - uses: actions/checkout@v4
      - uses: lamemakes/kicad-pics-action@dc08436b33a7fd6c920429e4279a3eaae8364674
        with:
          project-path: './2024-ornament/hardware/'
          project-name: 'tree-ornament'
          output-path: './2024-ornament/pics/'
