on: [push]

jobs:
  gen-image:
    runs-on: ubuntu-latest
    name: Generate images from a KiCad project
    steps:
      - uses: actions/checkout@v4
      - uses: lamemakes/kicad-pics-action@011eaa30f93b3ad354c019dee09c7e8624722d2f
        with:
          project-path: './hardware/'
          project-name: 'tree-ornament'
          output-path: './pics/'
