on: [push]

jobs:
  gen-image:
    runs-on: ubuntu-latest
    name: Generate images from a KiCad project
    steps:
      - uses: actions/checkout@v4
      - uses: lamemakes/kicad-pics-action@60efa5ccc0cd599e258df3ad47f0e0198a32f854
        with:
          project-path: 'hardware/'
          project-name: 'tree-ornament'
          output-path: 'pics/'
